version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: crypto_wallet_db
    environment:
      POSTGRES_DB: crypto_wallet
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
