CREATE TABLE wallet (
   id BIGSERIAL PRIMARY KEY,
   email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE token (
    id VARCHAR(255) PRIMARY KEY,
    symbol VARCHAR(50) NOT NULL UNIQUE,
    price DECIMAL(22,10) NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE asset (
   id BIGSERIAL PRIMARY KEY,
   quantity DECIMAL(22,10) NOT NULL,
   token_id VARCHAR(50) NOT NULL,
   wallet_id BIGINT NOT NULL,
   FOREIGN KEY (token_id) REFERENCES token(id) ON DELETE CASCADE,
   FOREIGN KEY (wallet_id) REFERENCES wallet(id) ON DELETE CASCADE
);
